spring:
  cloud:
    gateway:
      routes:
        # 如果请求参数url等于百度, 则跳转到https://www.baidu.com
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        # 如果请求参数url等于qq, 则跳转到https://www.qq.com
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq
