spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.48.129:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
  thymeleaf:
    cache: false
  redis:
    host: 192.168.48.129
  session:
    store-type: redis
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    # 虚拟主机
    virtual-host: /
    # 开启发送端发送确认，无论是否到达broker都会触发回调【发送端确认机制+本地事务表】
    publisher-confirm-type: correlated
    # 开启发送端抵达队列确认，消息未被队列接收时触发回调【发送端确认机制+本地事务表】
    publisher-returns: true
    # 消息在没有被队列接收时是否强行退回
    template:
      mandatory: true
    # 消费者手动确认模式，关闭自动确认，否则会消息丢失
    listener:
      simple:
        acknowledge-mode: manual

#seata:
#  tx-service-group: mygroup # 事务分组名称，要和服务端对应
#  service:
#    vgroup-mapping:
#      mygroup: default # key是事务分组名称 value要和服务端的机房名称保持一致


gulimall:
  thread:
    core-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10

# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000
